name: WorldTeleport
version: '1'
main: worldteleport.worldteleport.WorldTeleport
api-version: 1.19
authors: [ SakakiAruka ]
description: provide teleport system between worlds.
commands:
  home:
    permission: worldteleport.default
  wtp:
    permission: worldteleport.default
  homepointreload:
    permission: worldteleport.op

permissions:
  worldteleport.default:
    default: true
  worldteleport.op:
    default: op