name: WorldTeleport
version: '1'
main: worldteleport.worldteleport.WorldTeleport
api-version: 1.19
authors: [ SakakiAruka ]
description: provide teleport system between worlds.
commands:
  home:
    permission: worldteleport.home
  wtp:
    permission: worldteleport.wtp
  homepointreload:
    permission: worldteleport.settingsreload
